# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_EDGEQ_XGBE) += xgmac_main.o dwxgmac_core.o \
		xgmac_ptp.o xgmac_ethtool.o \
		hwif.o dwxgmac_dma.o dwxgmac_descs.o \
		xgmac_hwtstamp.o xgmac_tc.o mmc_core.o \
		xgmac_platform.o xgbe_ecpri.o xgbe_drv.o \
		xgbe_xpcs.o xgbe_misc.o xgbe_phy.o
