# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_EDGEQ) += raptor2-B0-titan.dtb
dtb-$(CONFIG_ARCH_EDGEQ) += raptor2-B0_f.dtb
dtb-$(CONFIG_ARCH_EDGEQ) += raptor2-B0-hawk.dtb
dtb-$(CONFIG_ARCH_EDGEQ) += raptor2-B0-hawk_f.dtb
