#include "sif_config.h"

#if B0_BUILD
/* SIF Routing table of all outputs. */
struct sif_routing_info_t sif_su_routing_table[MAX_SIF_TO_SU_EVENTS] = {
	/* SPU Event Start */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 0},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 1},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 2},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 3},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 4},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 5},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 6},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 7},
	/* SPU Events End */
	/* OTRX Event Start */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 8},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 9},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 10},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 11},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 12},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 13},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 14},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 15},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 16},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 17},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 18},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 19},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 20},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 21},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 22},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 23},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 24},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 25},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 26},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 27},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 28},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 29},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 30},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 31},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 32},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 33},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 34},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 35},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 36},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 37},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 38},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 39},
	/* OTRX Events End */
	/* BSS Events Start */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 40},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 41},
	{SIF_ROUTING_SU_TO_SU, 346, 42},			/* 1 PPS signal from XGMAC0 to BSS output */
	{SIF_ROUTING_REG_EVT_TO_SU, SIF_INVALID_EVENT, 43},	/* BSS Runtime ready */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 44},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 45},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 46},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 47},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 48},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 49},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 50},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 51},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 52},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 53},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 54},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 55},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 56},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 57},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 58},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 59},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 60},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 61},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 62},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 63},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 64},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 65},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 66},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 67},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 68},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 69},
	/* BSS Events End */
	/* CC Events Start */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 70},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 71},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 72},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 73},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 74},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 75},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 76},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 77},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 78},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 79},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 80},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 81},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 82},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 83},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 84},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 85},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 86},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 87},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 88},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 89},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 90},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 91},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 92},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 93},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 94},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 95},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 96},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 97},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 98},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 99},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 100},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 101},
	/* CC Events End */
	/* GPIO Events Start */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 102},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 103},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 104},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 105},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 106},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 107},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 108},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 109},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 110},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 111},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 112},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 113},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 114},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 115},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 116},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 117},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 118},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 119},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 120},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 121},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 122},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 123},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 124},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 125},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 126},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 127},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 128},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 129},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 130},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 131},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 132},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 133},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 134},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 135},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 136},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 137},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 138},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 139},
	{SIF_ROUTING_SU_TO_SU, 346, 140},	/* 1 PPS signal from XGMAC0 to GPIO38 */
	{SIF_ROUTING_SU_TO_SU, 211, 141},	/* 1 PPS signal from GPS (GPIO21) to GPIO39 */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 142},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 143},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 144},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 145},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 146},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 147},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 148},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 149},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 150},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 151},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 152},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 153},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 154},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 155},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 156},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 157},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 158},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 159},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 160},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 161},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 162},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 163},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 164},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 165},
	/* GPIO Events End */
	/* ECPRI Events Start */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 166},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 167},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 168},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 169},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 170},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 171},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 172},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 173},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 174},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 175},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 176},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 177},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 178},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 179},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 180},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 181},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 182},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 183},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 184},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 185},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 186},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 187},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 188},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 189},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 190},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 191},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 192},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 193},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 194},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 195},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 196},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 197},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 198},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 199},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 200},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 201},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 202},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 203},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 204},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 205},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 206},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 207},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 208},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 209},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 210},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 211},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 212},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 213},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 214},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 215},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 216},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 217},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 218},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 219},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 220},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 221},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 222},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 223},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 224},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 225},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 226},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 227},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 228},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 229},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 230},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 231},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 232},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 233},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 234},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 235},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 236},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 237},
	/* ECPRI Events End */
	/* IOSS Events Start */
	{SIF_ROUTING_SU_TO_SU, 211, 238},	/* 1 PPS signal from GPS (GPIO21) to XGMAC0 AUX_SNAP_0 */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 239},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 240},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 241},
	{SIF_ROUTING_SU_TO_SU, 211, 242},	/* 1 PPS signal from GPS (GPIO21) to XLGMAC1 AUX_SNAP_0 */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 243},
	{SIF_ROUTING_SU_TO_SU, 211, 244},	/* 1 PPS signal from GPS (GPIO21) to XLGMAC2 AUX_SNAP_0 */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 245},
	{SIF_ROUTING_SU_TO_SU, 211, 246},	/* 1 PPS signal from GPS (GPIO21) to XLGMAC3 AUX_SNAP_0 */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 247},
	{SIF_ROUTING_SU_TO_SU, 211, 248},	/* 1 PPS signal from GPS (GPIO21) to LINK1 XLGMAC AUX_SNAP_0 */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 249},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 250},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 251},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 252},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 253},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 254},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 255},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 256},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 257},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 258},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 259},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 260},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 261},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 262},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 263},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 264},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 265},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 266},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 267},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 268},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 269},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 270},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 271},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 272},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 273},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 274},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 275},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 276},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 277},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 278},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 279},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 280},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 281},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 282},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 283},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 284},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 285},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 286},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 287},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 288},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 289},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 290},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 291},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 292},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 293},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 294},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 295},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 296},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 297},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 298},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 299},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 300},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 301},
	/* IOSS Events End */
	/* PPU Events Start */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 302},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 303},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 304},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 305},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 306},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 307},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 308},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 309},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 310},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 311},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 312},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 313},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 314},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 315},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 316},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 317},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 318},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 319},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 320},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 321},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 322},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 323},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 324},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 325},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 326},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 327},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 328},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 329},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 330},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 331},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 332},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 333},
	/* PPU Events End */
	/* RESERVED Start */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 334},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 335},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 336},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 337},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 338},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 339},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 340},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 341},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 342},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 343},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 344},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 345},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 346},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 347},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 348},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 349},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 350},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 351},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 352},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 353},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 354},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 355},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 356},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 357},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 358},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 359},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 360},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 361},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 362},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 363},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 364},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 365},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 366},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 367},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 368},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 369},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 370},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 371},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 372},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 373},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 374},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 375},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 376},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 377},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 378},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 379},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 380},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 381},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 382},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 383},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 384},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 385},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 386},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 387},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 388},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 389},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 390},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 391},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 392},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 393},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 394},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 395},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 396},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 397},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 398},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 399},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 400},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 401},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 402},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 403},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 404},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 405},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 406},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 407},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 408},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 409},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 410},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 411},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 412},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 413},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 414},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 415},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 416},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 417},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 418},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 419},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 420},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 421},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 422},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 423},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 424},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 425},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 426},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 427},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 428},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 429},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 430},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 431},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 432},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 433},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 434},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 435},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 436},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 437},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 438},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 439},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 440},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 441},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 442},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 443},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 444},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 445},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 446},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 447},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 448},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 449},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 450},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 451},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 452},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 453},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 454},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 455},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 456},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 457},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 458},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 459},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 460},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 461},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 462},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 463},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 464},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 465},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 466},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 467},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 468},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 469},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 470},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 471},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 472},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 473},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 474},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 475},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 476},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 477},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 478},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 479},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 480},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 481},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 482},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 483},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 484},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 485},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 486},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 487},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 488},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 489},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 490},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 491},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 492},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 493},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 494},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 495},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 496},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 497},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 498},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 499},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 500},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 501},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 502},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 503},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 504},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 505},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 506},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 507},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 508},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 509},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 510},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 511},
	/* Reserved End */
};
#else
/* SIF Routing table of all outputs. */
struct sif_routing_info_t sif_routing_table[MAX_SIF_OUTPUT_EVENTS] = {
	/* SPU Event Start */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 0},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 1},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 2},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 3},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 4},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 5},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 6},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 7},
	/* SPU Events End */
	/* OTRX Event Start */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 8},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 9},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 10},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 11},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 12},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 13},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 14},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 15},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 16},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 17},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 18},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 19},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 20},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 21},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 22},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 23},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 24},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 25},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 26},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 27},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 28},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 29},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 30},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 31},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 32},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 33},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 34},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 35},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 36},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 37},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 38},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 39},
	/* OTRX Events End */
	/* BSS Events Start */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 40},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 41},
	{SIF_ROUTING_SU_TO_SU, 285, 42},			/* 1 PPS signal from XGMAC0 to BSS output */
	{SIF_ROUTING_REG_EVT_TO_SU, SIF_INVALID_EVENT, 43},	/* BSS Runtime ready */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 44},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 45},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 46},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 47},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 48},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 49},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 50},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 51},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 52},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 53},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 54},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 55},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 56},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 57},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 58},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 59},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 60},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 61},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 62},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 63},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 64},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 65},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 66},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 67},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 68},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 69},
	/* BSS Events End */
	/* CC Events Start */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 70},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 71},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 72},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 73},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 74},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 75},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 76},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 77},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 78},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 79},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 80},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 81},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 82},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 83},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 84},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 85},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 86},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 87},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 88},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 89},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 90},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 91},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 92},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 93},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 94},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 95},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 96},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 97},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 98},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 99},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 100},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 101},
	/* CC Events End */
	/* GPIO Events Start */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 102},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 103},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 104},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 105},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 106},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 107},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 108},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 109},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 110},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 111},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 112},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 113},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 114},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 115},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 116},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 117},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 118},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 119},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 120},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 121},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 122},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 123},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 124},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 125},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 126},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 127},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 128},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 129},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 130},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 131},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 132},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 133},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 134},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 135},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 136},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 137},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 138},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 139},
	{SIF_ROUTING_SU_TO_SU, 285, 140},	/* 1 PPS signal from XGMAC0 to GPIO38 */
	{SIF_ROUTING_SU_TO_SU, 151, 141},	/* 1 PPS signal from GPS (GPIO21) to GPIO39 */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 142},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 143},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 144},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 145},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 146},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 147},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 148},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 149},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 150},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 151},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 152},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 153},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 154},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 155},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 156},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 157},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 158},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 159},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 160},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 161},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 162},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 163},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 164},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 165},
	/* GPIO Events End */
	/* IOSS Events Start */
	{SIF_ROUTING_SU_TO_SU, 151, 230},	/* 1 PPS signal from GPS (GPIO21) to XGMAC0 AUX_SNAP_0 */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 167},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 168},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 169},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 170},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 171},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 172},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 173},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 174},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 175},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 176},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 177},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 178},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 179},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 180},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 181},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 182},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 183},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 184},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 185},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 186},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 187},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 188},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 189},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 190},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 191},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 192},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 193},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 194},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 195},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 196},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 197},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 198},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 199},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 200},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 201},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 202},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 203},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 204},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 205},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 206},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 207},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 208},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 209},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 210},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 211},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 212},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 213},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 214},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 215},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 216},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 217},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 218},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 219},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 220},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 221},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 222},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 223},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 224},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 225},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 226},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 227},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 228},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 229},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 230},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 231},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 232},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 233},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 234},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 235},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 236},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 237},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 238},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 239},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 240},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 241},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 242},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 243},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 244},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 245},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 246},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 247},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 248},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 249},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 250},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 251},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 252},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 253},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 254},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 255},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 256},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 257},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 258},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 259},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 260},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 261},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 262},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 263},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 264},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 265},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 266},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 267},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 268},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 269},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 270},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 271},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 272},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 273},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 274},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 275},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 276},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 277},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 278},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 279},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 280},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 281},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 282},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 283},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 284},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 285},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 286},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 287},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 288},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 289},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 290},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 291},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 292},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 293},
	/* IOSS Events End */
	/* PPU Events Start */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 294},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 295},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 296},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 297},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 298},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 299},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 300},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 301},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 302},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 303},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 304},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 305},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 306},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 307},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 308},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 309},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 310},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 311},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 312},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 313},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 314},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 315},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 316},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 317},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 318},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 319},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 320},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 321},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 322},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 323},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 324},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 325},
	/* PPU Events End */
	/* RESERVED Start */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 326},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 327},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 328},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 329},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 330},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 331},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 332},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 333},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 334},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 335},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 336},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 337},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 338},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 339},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 340},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 341},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 342},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 343},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 344},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 345},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 346},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 347},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 348},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 349},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 350},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 351},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 352},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 353},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 354},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 355},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 356},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 357},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 358},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 359},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 360},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 361},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 362},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 363},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 364},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 365},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 366},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 367},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 368},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 369},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 370},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 371},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 372},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 373},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 374},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 375},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 376},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 377},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 378},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 379},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 380},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 381},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 382},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 383},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 384},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 385},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 386},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 387},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 388},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 389},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 390},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 391},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 392},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 393},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 394},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 395},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 396},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 397},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 398},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 399},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 400},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 401},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 402},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 403},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 404},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 405},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 406},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 407},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 408},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 409},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 410},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 411},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 412},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 413},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 414},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 415},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 416},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 417},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 418},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 419},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 420},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 421},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 422},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 423},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 424},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 425},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 426},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 427},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 428},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 429},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 430},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 431},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 432},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 433},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 434},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 435},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 436},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 437},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 438},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 439},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 440},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 441},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 442},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 443},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 444},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 445},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 446},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 447},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 448},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 449},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 450},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 451},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 452},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 453},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 454},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 455},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 456},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 457},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 458},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 459},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 460},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 461},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 462},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 463},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 464},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 465},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 466},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 467},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 468},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 469},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 470},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 471},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 472},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 473},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 474},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 475},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 476},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 477},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 478},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 479},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 480},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 481},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 482},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 483},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 484},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 485},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 486},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 487},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 488},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 489},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 490},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 491},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 492},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 493},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 494},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 495},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 496},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 497},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 498},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 499},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 500},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 501},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 502},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 503},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 504},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 505},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 506},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 507},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 508},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 509},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 510},
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 511},
	/* Reserved End */
	/* GIC-SPI Start */
	{SIF_ROUTING_SU_TO_E1, 50, 0},		/* bss_su_gpio_out[0] */
	{SIF_ROUTING_SU_TO_E1, 51, 1},		/* bss_su_gpio_out[1] */
	{SIF_ROUTING_SU_TO_E1, 52, 2},		/* bss_su_gpio_out[2] */
	{SIF_ROUTING_SU_TO_E1, 53, 3},		/* bss_su_gpio_out[3] */
	{SIF_ROUTING_SU_TO_E1, 415, 4},		/* uart3_intr */
	{SIF_ROUTING_SU_TO_E1, 416, 5},		/* uart2_intr */
	{SIF_ROUTING_SU_TO_E1, 417, 6},		/* uart1_intr */
	{SIF_ROUTING_SU_TO_E1, 418, 7},		/* i2c3_int */
	{SIF_ROUTING_SU_TO_E1, 419, 8},		/* i2c2_int */
	{SIF_ROUTING_SU_TO_E1, 420, 9},		/* i2c1_int */
	{SIF_ROUTING_SU_TO_E1, 421, 10},	/* bss_spim_2_boot_intr */
	{SIF_ROUTING_SU_TO_E1, 422, 11},	/* bss_spim_1_boot_intr */
	{SIF_ROUTING_SU_TO_E1, 423, 12},	/* bss_nf_int (norflash spi controller) */
	{SIF_ROUTING_SU_TO_E1, 424, 13},	/* emmc_wakeup_intr */
	{SIF_ROUTING_SU_TO_E1, 425, 14},	/* emmc_intr */
	{SIF_ROUTING_SU_TO_E1, 426, 15},	/* usim_intr */
	{SIF_ROUTING_SU_TO_E1, 427, 16},	/* crypto_int */
	{SIF_ROUTING_SU_TO_E1, 428, 17},	/* pmic_int */
	{SIF_ROUTING_SU_TO_E1, 429, 18},	/* nmi_int */
	{SIF_ROUTING_SU_TO_E1, 430, 19},	/* bss_su_gpio_out[4] - 1 PPS Timer latch event from BSS to E1 */
	{SIF_ROUTING_SU_TO_E1, 282, 20},	/* usb_interrupt[0] */
	{SIF_ROUTING_SU_TO_E1, 283, 21},	/* usb_interrupt[1] */
	{SIF_ROUTING_SU_TO_E1, 284, 22},	/* USB PHY DRVVBUS0 */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 23},
	{SIF_ROUTING_SU_TO_E1, 286, 24},	/* smlh_link_up */
	{SIF_ROUTING_SU_TO_E1, 287, 25},	/* msi_ctrl_int */
	{SIF_ROUTING_SU_TO_E1, 288, 26},	/* hp_int */
	{SIF_ROUTING_SU_TO_E1, 289, 27},	/* pcie0_int_evt_radm_inta_asserted */
	{SIF_ROUTING_SU_TO_E1, 290, 28},	/* pcie0_int_evt_radm_intb_asserted */
	{SIF_ROUTING_SU_TO_E1, 291, 29},	/* pcie0_int_evt_radm_intc_asserted */
	{SIF_ROUTING_SU_TO_E1, 292, 30},	/* pcie0_int_evt_radm_intd_asserted */
	{SIF_ROUTING_SU_TO_E1, 293, 31},	/* CCIX edma_int[0] */
	{SIF_ROUTING_SU_TO_E1, 294, 32},	/* CCIX edma_int[1] */
	{SIF_ROUTING_SU_TO_E1, 295, 33},	/* CCIX radm_inta_asserted */
	{SIF_ROUTING_SU_TO_E1, 296, 34},	/* CCIX radm_intb_asserted */
	{SIF_ROUTING_SU_TO_E1, 297, 35},	/* CCIX radm_intc_asserted */
	{SIF_ROUTING_SU_TO_E1, 298, 36},	/* CCIX radm_intd_asserted */
	{SIF_ROUTING_SU_TO_E1, 299, 37},	/* PCIE edma_int[0] */
	{SIF_ROUTING_SU_TO_E1, 300, 38},	/* PCIE edma_int[1] */
	{SIF_ROUTING_SU_TO_E1, 301, 39},	/* PCIE edma_int[2] */
	{SIF_ROUTING_SU_TO_E1, 302, 40},	/* PCIE edma_int[3] */
	{SIF_ROUTING_SU_TO_E1, 303, 41},	/* PCIE edma_int[4] */
	{SIF_ROUTING_SU_TO_E1, 304, 42},	/* PCIE edma_int[8] */
	{SIF_ROUTING_SU_TO_E1, 305, 43},	/* PCIE edma_int[9] */
	{SIF_ROUTING_SU_TO_E1, 306, 44},	/* PCIE edma_int[10] */
	{SIF_ROUTING_SU_TO_E1, 307, 45},	/* PCIE edma_int[11] */
	{SIF_ROUTING_SU_TO_E1, 308, 46},	/* PCIE edma_int[12] */
	{SIF_ROUTING_SU_TO_E1, 309, 47},	/* ptn_xgmac_xgmac0_sbd_perch_tx_intr_o_00 */
	{SIF_ROUTING_SU_TO_E1, 310, 48},	/* ptn_xgmac_xgmac0_sbd_perch_tx_intr_o_01 */
	{SIF_ROUTING_SU_TO_E1, 311, 49},	/* ptn_xgmac_xgmac0_sbd_perch_tx_intr_o_02 */
	{SIF_ROUTING_SU_TO_E1, 312, 50},	/* ptn_xgmac_xgmac0_sbd_perch_tx_intr_o_03 */
	{SIF_ROUTING_SU_TO_E1, 313, 51},	/* ptn_xgmac_xgmac1_sbd_perch_tx_intr_o_00 */
	{SIF_ROUTING_SU_TO_E1, 314, 52},	/* ptn_xgmac_xgmac1_sbd_perch_tx_intr_o_01 */
	{SIF_ROUTING_SU_TO_E1, 315, 53},	/* ptn_xgmac_xgmac1_sbd_perch_tx_intr_o_02 */
	{SIF_ROUTING_SU_TO_E1, 316, 54},	/* ptn_xgmac_xgmac1_sbd_perch_tx_intr_o_03 */
	{SIF_ROUTING_SU_TO_E1, 317, 55},	/* ptn_xgmac_xgmac2_sbd_perch_tx_intr_o_00 */
	{SIF_ROUTING_SU_TO_E1, 318, 56},	/* ptn_xgmac_xgmac2_sbd_perch_tx_intr_o_01 */
	{SIF_ROUTING_SU_TO_E1, 319, 57},	/* ptn_xgmac_xgmac2_sbd_perch_tx_intr_o_02 */
	{SIF_ROUTING_SU_TO_E1, 320, 58},	/* ptn_xgmac_xgmac2_sbd_perch_tx_intr_o_03 */
	{SIF_ROUTING_SU_TO_E1, 321, 59},	/* ptn_xgmac_xgmac3_sbd_perch_tx_intr_o_00 */
	{SIF_ROUTING_SU_TO_E1, 322, 60},	/* ptn_xgmac_xgmac3_sbd_perch_tx_intr_o_01 */
	{SIF_ROUTING_SU_TO_E1, 323, 61},	/* ptn_xgmac_xgmac3_sbd_perch_tx_intr_o_02 */
	{SIF_ROUTING_SU_TO_E1, 324, 62},	/* ptn_xgmac_xgmac3_sbd_perch_tx_intr_o_03 */
	{SIF_ROUTING_SU_TO_E1, 325, 63},	/* ptn_xgmac_xgmac0_sbd_perch_rx_intr_o_00 */
	{SIF_ROUTING_SU_TO_E1, 326, 64},	/* ptn_xgmac_xgmac0_sbd_perch_rx_intr_o_01 */
	{SIF_ROUTING_SU_TO_E1, 327, 65},	/* ptn_xgmac_xgmac0_sbd_perch_rx_intr_o_02 */
	{SIF_ROUTING_SU_TO_E1, 328, 66},	/* ptn_xgmac_xgmac0_sbd_perch_rx_intr_o_03 */
	{SIF_ROUTING_SU_TO_E1, 329, 67},	/* ptn_xgmac_xgmac1_sbd_perch_rx_intr_o_00 */
	{SIF_ROUTING_SU_TO_E1, 330, 68},	/* ptn_xgmac_xgmac1_sbd_perch_rx_intr_o_01 */
	{SIF_ROUTING_SU_TO_E1, 331, 69},	/* ptn_xgmac_xgmac1_sbd_perch_rx_intr_o_02 */
	{SIF_ROUTING_SU_TO_E1, 332, 70},	/* ptn_xgmac_xgmac1_sbd_perch_rx_intr_o_03 */
	{SIF_ROUTING_SU_TO_E1, 333, 71},	/* ptn_xgmac_xgmac2_sbd_perch_rx_intr_o_00 */
	{SIF_ROUTING_SU_TO_E1, 334, 72},	/* ptn_xgmac_xgmac2_sbd_perch_rx_intr_o_01 */
	{SIF_ROUTING_SU_TO_E1, 335, 73},	/* ptn_xgmac_xgmac2_sbd_perch_rx_intr_o_02 */
	{SIF_ROUTING_SU_TO_E1, 336, 74},	/* ptn_xgmac_xgmac2_sbd_perch_rx_intr_o_03 */
	{SIF_ROUTING_SU_TO_E1, 337, 75},	/* ptn_xgmac_xgmac3_sbd_perch_rx_intr_o_00 */
	{SIF_ROUTING_SU_TO_E1, 338, 76},	/* ptn_xgmac_xgmac3_sbd_perch_rx_intr_o_01 */
	{SIF_ROUTING_SU_TO_E1, 339, 77},	/* ptn_xgmac_xgmac3_sbd_perch_rx_intr_o_02 */
	{SIF_ROUTING_SU_TO_E1, 340, 78},	/* ptn_xgmac_xgmac3_sbd_perch_rx_intr_o_03 */
	{SIF_ROUTING_SU_TO_E1, 341, 79},	/* XLGMAC sbd_intr_0 */
	{SIF_ROUTING_SU_TO_E1, 342, 80},	/* XGMAC3 sbd_intr_0 */
	{SIF_ROUTING_SU_TO_E1, 343, 81},	/* XGMAC2 sbd_intr_0 */
	{SIF_ROUTING_SU_TO_E1, 344, 82},	/* XGMAC1 sbd_intr_0 */
	{SIF_ROUTING_SU_TO_E1, 345, 83},	/* XGMAC0 sbd_intr_0 */
	{SIF_ROUTING_SU_TO_E1, 194, 84},	/* Reserved for CMN */
	{SIF_ROUTING_SU_TO_E1, 195, 85},	/* Reserved for CMN */
	{SIF_ROUTING_SU_TO_E1, 200, 86},	/* tcu_ras_irpt */
	{SIF_ROUTING_SU_TO_E1, 201, 87},	/* tcu_pri_q_irpt_ns */
	{SIF_ROUTING_SU_TO_E1, 202, 88},	/* tcu_pmu_irpt */
	{SIF_ROUTING_SU_TO_E1, 203, 89},	/* tcu_global_irpt_s */
	{SIF_ROUTING_SU_TO_E1, 204, 90},	/* tcu_global_irpt_ns */
	{SIF_ROUTING_SU_TO_E1, 205, 91},	/* tcu_evento */
	{SIF_ROUTING_SU_TO_E1, 206, 92},	/* tcu_event_q_irpt_s */
	{SIF_ROUTING_SU_TO_E1, 207, 93},	/* tcu_event_q_irpt_ns */
	{SIF_ROUTING_SU_TO_E1, 208, 94},	/* tcu_cmd_sync_irpt_s */
	{SIF_ROUTING_SU_TO_E1, 209, 95},	/* tcu_cmd_sync_irpt_ns */
	{SIF_ROUTING_SU_TO_E1, 210, 96},	/* tbu_0_ras_irpt */
	{SIF_ROUTING_SU_TO_E1, 211, 97},	/* tbu_0_pmu_irpt */
	{SIF_ROUTING_E1_TO_E1, 6, 98},		/* nCLUSTERPMUIRQ */
	{SIF_ROUTING_E1_TO_E1, 244, 99},	/* nCLUSTERPMUIRQ */
	{SIF_ROUTING_E1_TO_E1, 252, 100},	/* uart0_intr */
	{SIF_ROUTING_E1_TO_E1, 253, 101},	/* uart1_intr */
	{SIF_ROUTING_E1_TO_E1, 254, 102},	/* trng_intr */
	{SIF_ROUTING_E1_TO_E1, 255, 103},	/* pvt_mon_th_cross_int */
	{SIF_ROUTING_SU_TO_E1, 130, 104},	/* Multi SoC GPIO Interrupts */
	{SIF_ROUTING_SU_TO_E1, 131, 105},	/* Multi SoC GPIO Interrupts */
	{SIF_ROUTING_SU_TO_E1, 132, 106},	/* Multi SoC GPIO Interrupts */
	{SIF_ROUTING_SU_TO_E1, 133, 107},	/* Multi SoC GPIO Interrupts */
	{SIF_ROUTING_SU_TO_E1, 134, 108},	/* Multi SoC GPIO Interrupts */
	{SIF_ROUTING_SU_TO_E1, 135, 109},	/* Multi SoC GPIO Interrupts */
	{SIF_ROUTING_SU_TO_E1, 136, 110},	/* Multi SoC GPIO Interrupts */
	{SIF_ROUTING_SU_TO_E1, 137, 111},	/* Multi SoC GPIO Interrupts */
	{SIF_ROUTING_SU_TO_E1, 138, 112},	/* Multi SoC GPIO Interrupts */
	{SIF_ROUTING_SU_TO_E1, 139, 113},	/* Multi SoC GPIO Interrupts */
	{SIF_ROUTING_SU_TO_E1, 140, 114},	/* Multi SoC GPIO Interrupts */
	{SIF_ROUTING_SU_TO_E1, 141, 115},	/* Multi SoC GPIO Interrupts */
	{SIF_ROUTING_SU_TO_E1, 142, 116},	/* Multi SoC GPIO Interrupts */
	{SIF_ROUTING_SU_TO_E1, 143, 117},	/* Multi SoC GPIO Interrupts */
	{SIF_ROUTING_SU_TO_E1, 144, 118},	/* Multi SoC GPIO Interrupts */
	{SIF_ROUTING_SU_TO_E1, 145, 119},	/* Multi SoC GPIO Interrupts */
	{SIF_ROUTING_SU_TO_E1, 410, 120},	/* dwcddrphy_int_n */
	{SIF_ROUTING_SU_TO_E1, 411, 121},	/* ddr_ctl_sbr_done_intr */
	{SIF_ROUTING_SU_TO_E1, 412, 122},	/* ddr_ctl_ecc_uncorrected_err_intr */
	{SIF_ROUTING_SU_TO_E1, 413, 123},	/* ddr_ctl_ecc_corrected_err_intr */
	{SIF_ROUTING_SU_TO_E1, 414, 124},	/* ddr_ctl_alert_err_intr */
	{SIF_ROUTING_SU_TO_E1, 346, 125},	/* DUAL_SU.SU0.out_evts[0] - CFG to MACRT */
	{SIF_ROUTING_SU_TO_E1, 347, 126},	/* DUAL_SU.SU0.out_evts[1] */
	{SIF_ROUTING_SU_TO_E1, 348, 127},	/* DUAL_SU.SU0.out_evts[2] */
	{SIF_ROUTING_SU_TO_E1, 349, 128},	/* DUAL_SU.SU0.out_evts[3] */
	{SIF_ROUTING_SU_TO_E1, 350, 129},	/* DUAL_SU.SU1.out_evts[0] - CFG to MACRT */
	{SIF_ROUTING_SU_TO_E1, 351, 130},	/* DUAL_SU.SU1.out_evts[1] - Monitor mode */
	{SIF_ROUTING_SU_TO_E1, 352, 131},	/* DUAL_SU.SU1.out_evts[2] */
	{SIF_ROUTING_SU_TO_E1, 353, 132},	/* DUAL_SU.SU1.out_evts[3] */
	{SIF_ROUTING_SU_TO_E1, 354, 133},	/* CRSS.out_evts[0] */
	{SIF_ROUTING_SU_TO_E1, 355, 134},	/* CRSS.out_evts[1] */
	{SIF_ROUTING_SU_TO_E1, 356, 135},	/* CRSS.out_evts[2] */
	{SIF_ROUTING_SU_TO_E1, 357, 136},	/* CRSS.out_evts[3] */
	{SIF_ROUTING_SU_TO_E1, 358, 137},	/* CRSS.out_evts[4] */
	{SIF_ROUTING_SU_TO_E1, 359, 138},	/* CRSS.out_evts[5] */
	{SIF_ROUTING_SU_TO_E1, 360, 139},	/* CRSS.out_evts[6] */
	{SIF_ROUTING_SU_TO_E1, 361, 140},	/* CRSS.out_evts[7] */
	{SIF_ROUTING_SU_TO_E1, 362, 141},	/* CRSS.out_evts[8] */
	{SIF_ROUTING_SU_TO_E1, 363, 142},	/* CRSS.out_evts[9] */
	{SIF_ROUTING_SU_TO_E1, 364, 143},	/* CRSS.out_evts[10] */
	{SIF_ROUTING_SU_TO_E1, 365, 144},	/* CRSS.out_evts[11] */
	{SIF_ROUTING_SU_TO_E1, 366, 145},	/* CRSS.out_evts[12] */
	{SIF_ROUTING_SU_TO_E1, 367, 146},	/* CRSS.out_evts[13] */
	{SIF_ROUTING_SU_TO_E1, 368, 147},	/* CRSS.out_evts[14] */
	{SIF_ROUTING_SU_TO_E1, 369, 148},	/* CRSS.out_evts[15] */
	{SIF_ROUTING_SU_TO_E1, 370, 149},	/* CRSS.out_evts[16] */
	{SIF_ROUTING_SU_TO_E1, 371, 150},	/* CRSS.out_evts[17] */
	{SIF_ROUTING_SU_TO_E1, 372, 151},	/* CRSS.out_evts[18] */
	{SIF_ROUTING_SU_TO_E1, 373, 152},	/* CRSS.out_evts[19] */
	{SIF_ROUTING_SU_TO_E1, 374, 153},	/* CRSS.out_evts[20] */
	{SIF_ROUTING_SU_TO_E1, 375, 154},	/* CRSS.out_evts[21] */
	{SIF_ROUTING_SU_TO_E1, 376, 155},	/* CRSS.out_evts[22] */
	{SIF_ROUTING_SU_TO_E1, 377, 156},	/* CRSS.out_evts[23] */
	{SIF_ROUTING_SU_TO_E1, 378, 157},	/* CRSS.out_evts[24] */
	{SIF_ROUTING_SU_TO_E1, 379, 158},	/* CRSS.out_evts[25] */
	{SIF_ROUTING_SU_TO_E1, 380, 159},	/* CRSS.out_evts[26] */
	{SIF_ROUTING_SU_TO_E1, 381, 160},	/* CRSS.out_evts[27] */
	{SIF_ROUTING_SU_TO_E1, 382, 161},	/* CRSS.out_evts[28] */
	{SIF_ROUTING_SU_TO_E1, 383, 162},	/* CRSS.out_evts[29] */
	{SIF_ROUTING_SU_TO_E1, 384, 163},	/* CRSS.out_evts[30] */
	{SIF_ROUTING_SU_TO_E1, 385, 164},	/* PVTMON.intr */
	{SIF_ROUTING_SU_TO_E1, 386, 165},	/* MCDMA.out_evts[0] */
	{SIF_ROUTING_SU_TO_E1, 387, 166},	/* MCDMA.out_evts[1] */
	{SIF_ROUTING_SU_TO_E1, 388, 167},	/* MCDMA.out_evts[2] */
	{SIF_ROUTING_SU_TO_E1, 389, 168},	/* MCDMA.out_evts[3] */
	{SIF_ROUTING_SU_TO_E1, 390, 169},	/* MXL0.out_evts[0] */
	{SIF_ROUTING_SU_TO_E1, 391, 170},	/* MXL0.out_evts[1] */
	{SIF_ROUTING_SU_TO_E1, 392, 171},	/* MXL0.out_evts[2] */
	{SIF_ROUTING_SU_TO_E1, 393, 172},	/* MXL0.out_evts[3] */
	{SIF_ROUTING_SU_TO_E1, 394, 173},	/* MXL0.out_evts[4] */
	{SIF_ROUTING_SU_TO_E1, 395, 174},	/* MXL0.out_evts[5] */
	{SIF_ROUTING_SU_TO_E1, 396, 175},	/* MXL0.out_evts[6] */
	{SIF_ROUTING_SU_TO_E1, 397, 176},	/* MXL0.out_evts[7] */
	{SIF_ROUTING_SU_TO_E1, 398, 177},	/* MXL0.out_evts[8] */
	{SIF_ROUTING_SU_TO_E1, 399, 178},	/* MXL0.out_evts[9] */
	{SIF_ROUTING_SU_TO_E1, 400, 179},	/* MXL1.out_evts[0] */
	{SIF_ROUTING_SU_TO_E1, 401, 180},	/* MXL1.out_evts[1] */
	{SIF_ROUTING_SU_TO_E1, 402, 181},	/* MXL1.out_evts[2] */
	{SIF_ROUTING_SU_TO_E1, 403, 182},	/* MXL1.out_evts[3] */
	{SIF_ROUTING_SU_TO_E1, 404, 183},	/* MXL1.out_evts[4] */
	{SIF_ROUTING_SU_TO_E1, 405, 184},	/* MXL1.out_evts[5] */
	{SIF_ROUTING_SU_TO_E1, 406, 185},	/* MXL1.out_evts[6] */
	{SIF_ROUTING_SU_TO_E1, 407, 186},	/* MXL1.out_evts[7] */
	{SIF_ROUTING_SU_TO_E1, 408, 187},	/* MXL1.out_evts[8] */
	{SIF_ROUTING_SU_TO_E1, 409, 188},	/* MXL1.out_evts[9] */
	{SIF_ROUTING_E1_TO_E1, 7, 189},		/* E1-PPUSS to E1 CPUSS GPO Event */
	{SIF_ROUTING_E1_TO_E1, 8, 190},		/* E1-PPUSS to E1 CPUSS GPO Event */
	{SIF_ROUTING_E1_TO_E1, 9, 191},		/* E1-PPUSS to E1 CPUSS GPO Event */
	{SIF_ROUTING_E1_TO_E1, 10, 192},	/* E1-PPUSS to E1 CPUSS GPO Event */
	{SIF_ROUTING_E1_TO_E1, 11, 193},	/* E1-PPUSS to E1 CPUSS GPO Event */
	{SIF_ROUTING_E1_TO_E1, 12, 194},	/* E1-PPUSS to E1 CPUSS GPO Event */
	{SIF_ROUTING_E1_TO_E1, 13, 195},	/* E1-PPUSS to E1 CPUSS GPO Event */
	{SIF_ROUTING_E1_TO_E1, 14, 196},	/* E1-PPUSS to E1 CPUSS GPO Event */
	{SIF_ROUTING_E1_TO_E1, 64, 197},	/* E1-CPUSS to E1 PPUSS GPO Event */
	{SIF_ROUTING_E1_TO_E1, 65, 198},	/* E1-CPUSS to E1 PPUSS GPO Event */
	{SIF_ROUTING_E1_TO_E1, 66, 199},	/* E1-CPUSS to E1 PPUSS GPO Event */
	{SIF_ROUTING_E1_TO_E1, 67, 200},	/* E1-CPUSS to E1 PPUSS GPO Event */
	{SIF_ROUTING_E1_TO_E1, 68, 201},	/* E1-CPUSS to E1 PPUSS GPO Event */
	{SIF_ROUTING_E1_TO_E1, 69, 202},	/* E1-CPUSS to E1 PPUSS GPO Event */
	{SIF_ROUTING_E1_TO_E1, 70, 203},	/* E1-CPUSS to E1 PPUSS GPO Event */
	{SIF_ROUTING_E1_TO_E1, 71, 204},	/* E1-CPUSS to E1 PPUSS GPO Event */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 205},	/* Reserved for multi OS communication */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 206},	/* Reserved for multi OS communication */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 207},	/* Reserved for multi OS communication */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 208},	/* Reserved for multi OS communication */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 209},	/* Reserved for multi OS communication */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 210},	/* Reserved for multi OS communication */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 211},	/* Reserved for multi OS communication */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 212},	/* Reserved for multi OS communication */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 213},	/* Reserved for multi OS communication */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 214},	/* Reserved for multi OS communication */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 215},	/* Reserved for multi OS communication */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 216},	/* Reserved for multi OS communication */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 217},	/* Reserved for multi OS communication */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 218},	/* Reserved for multi OS communication */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 219},	/* Reserved for multi OS communication */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 220},	/* Reserved for multi OS communication */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 221},	/* TBD */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 222},	/* TBD */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 223},	/* TBD */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 224},	/* TBD */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 225},	/* TBD */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 226},	/* TBD */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 227},	/* TBD */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 228},	/* TBD */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 229},	/* TBD */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 230},	/* TBD */
	{SIF_ROUTING_SU_TO_E1, 151, 231},	/* 1 PPS signal from GPS (GPIO21) to Linux */
	{SIF_ROUTING_SU_TO_E1, 18, 232},	/* OTRX - GPO0 QSU0 */
	{SIF_ROUTING_SU_TO_E1, 22, 233},	/* OTRX - GPO0 QSU1 */
	{SIF_ROUTING_SU_TO_E1, 26, 234},	/* OTRX - GPO0 QSU2 */
	{SIF_ROUTING_SU_TO_E1, 30, 235},	/* OTRX - GPO0 QSU3 */
	{SIF_ROUTING_SU_TO_E1, 34, 236},	/* OTRX - GPO0 QSU4 */
	{SIF_ROUTING_SU_TO_E1, 38, 237},	/* OTRX - GPO0 QSU5 */
	{SIF_ROUTING_SU_TO_E1, 42, 238},	/* OTRX - GPO0 QSU6 */
	{SIF_ROUTING_SU_TO_E1, 46, 239},	/* OTRX - GPO0 QSU7 */
	/* Register based events */
	{SIF_ROUTING_REG_EVT_TO_E1, 0, 240},	/* Any SU to Linux E1 - Error Interrupt */
	{SIF_ROUTING_REG_EVT_TO_E1, 0, 241},	/* Any SU to Linux E1 - Error Interrupt */
	{SIF_ROUTING_REG_EVT_TO_E1, 0, 242},	/* Any SU to Firmware/Linux E1 - Error Interrupt */
	{SIF_ROUTING_REG_EVT_TO_E1, 0, 243},	/* Any SU to Firmware/Linux E1 - Error Interrupt */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 244},	/* Reserved for SIF Reg interrupt. Can be used for SU to CPUSS/PPUSS or PCIe MSI */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 245},	/* Reserved for SIF Reg interrupt. Can be used for SU to CPUSS/PPUSS or PCIe MSI */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 246},	/* Reserved for SIF Reg interrupt. Can be used for SU to CPUSS/PPUSS or PCIe MSI */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 247},	/* Reserved for SIF Reg interrupt. Can be used for SU to CPUSS/PPUSS or PCIe MSI */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 248},	/* Reserved for SIF Reg interrupt. Can be used for SU to CPUSS/PPUSS or PCIe MSI */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 249},	/* Reserved for SIF Reg interrupt. Can be used for SU to CPUSS/PPUSS or PCIe MSI */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 250},	/* Reserved for SIF Reg interrupt. Can be used for SU to CPUSS/PPUSS or PCIe MSI */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 251},	/* Reserved for SIF Reg interrupt. Can be used for SU to CPUSS/PPUSS or PCIe MSI */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 252},	/* Reserved for SIF Reg interrupt. Can be used for SU to CPUSS/PPUSS or PCIe MSI */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 253},	/* Reserved for SIF Reg interrupt. Can be used for SU to CPUSS/PPUSS or PCIe MSI */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 254},	/* Reserved for SIF Reg interrupt. Can be used for SU to CPUSS/PPUSS or PCIe MSI */
	{SIF_ROUTING_UNUSED, SIF_INVALID_EVENT, 255},	/* Reserved for SIF Reg interrupt. Can be used for SU to CPUSS/PPUSS or PCIe MSI */
	/* GIC-SPI End */
};
#endif
