# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2020 EdgeQ

obj-y	+= raptor2.o
obj-y 	+= raptor2_eeprom.o
obj-y 	+= raptor2_adi_dpll.o
obj-$(CONFIG_CMD_SET_AVS) += raptor2_avs.o
obj-$(CONFIG_CMD_RAPTOR_FUSE) += fuse-raptor.o
obj-$(CONFIG_CMD_SET_VDD) += raptor_set_vdd.o
obj-y += jesdinit/
