# SPDX-License-Identifier: GPL-2.0+
# Copyright (c) 2020 EdgeQ Inc

obj-y += xgbe_xgmac.o
obj-$(CONFIG_RAPTOR_FAMILY) += xgbe_misc.o
obj-$(CONFIG_EQXPCS) += xgbe_xpcs.o
obj-$(CONFIG_DM_ETH_PHY) += xgbe_phy.o
