/* SPDX-License-Identifier: GPL-2.0+
 *
 * Copyright (c) 2023 EdgeQ
 *
 * Autogenerated File: Generated via EEPROM_FLASHER Tool
 */

#ifndef _EEPROM_DATA_H_
#define _EEPROM_DATA_H_

#define TOTAL_GROUPS 7
#define GROUP_EEPROM_INFO 0
#define GROUP_BOARD_CONFIGS 1
#define GROUP_PCIE_USB_CONFIGS 2
#define GROUP_RFIC_CONFIGS 3
#define GROUP_ETHERNET_CONFIGS 4
#define GROUP_MISC_CONFIGS 5
#define GROUP_JESD_CONFIGS 6
#define CRC32_TYPE uint32_t

struct eeprom_info {
	uint32_t crc32;
	uint32_t signature;
	uint32_t size;
	uint16_t version;
	uint8_t reserved[18];
} __packed; /*struct eeprom_info*/

struct board_configs {
	uint32_t crc32;
	uint8_t board_serial_number[16];
	uint32_t board_target_usecase;
	uint32_t board_version;
	uint64_t soc_chip_id;
	uint32_t soc_chip_silicon_corner;
	uint32_t soc_package_marking_lot;
	uint32_t boot_mode_setting;
	uint64_t device_uid0;
	uint64_t device_uid1;
	uint64_t device_uid2;
	uint64_t device_uid3;
	uint8_t product_config[64];
	uint32_t ddr_config;
	uint8_t link1_status;
	uint8_t link2_status;
	uint8_t link3_status;
	uint8_t link4_status;
	uint8_t reserved[104];
} __packed; /*struct board_configs*/

struct pcie_usb_configs {
	uint32_t crc32;
	uint16_t active_pcie_interfaces;
	uint64_t pcie_id;
	uint64_t usb_id;
	uint8_t reserved[42];
} __packed; /*struct pcie_usb_configs*/

struct rfic_configs {
	uint32_t crc32;
	uint32_t status;
	uint32_t serial;
	uint32_t version;
	uint32_t assembly_option;
	uint8_t rf1_card_type;
	uint8_t rf2_card_type;
	uint8_t reserved[10];
} __packed; /*struct rfic_configs*/

struct ethernet_configs {
	uint32_t crc32;
	uint16_t max_interfaces;
	uint16_t active_interfaces;
	uint16_t ethlink;
	uint16_t ethact;
	uint8_t ethspeeds[6];
	uint8_t mac0[6];
	uint8_t mac1[6];
	uint8_t mac2[6];
	uint8_t mac3[6];
	uint8_t mac4[6];
	uint8_t ecpri_bitmap;
	uint8_t reserved[79];
} __packed; /*struct ethernet_configs*/

struct misc_configs {
	uint32_t crc32;
	uint32_t active_misc_interfaces;
	uint32_t pmic_configuration_version;
	uint32_t pcb_assembly_option;
	uint32_t pcb_rework_serivce_code;
	uint32_t dctxo_initial_value;
	uint8_t pvt_mon_cal[16];
	uint8_t reserved[88];
} __packed; /*struct misc_configs*/

struct jesd_configs {
	uint32_t crc32;
	uint16_t link3_lane_select;
	uint16_t link4_lane_select;
	uint8_t link3_lane_polarity;
	uint8_t link4_lane_polarity;
	uint8_t link_speed;
	uint8_t reserved[373];
} __packed; /*struct jesd_configs*/

/* EEPROM main structure */
struct eeprom_data {
	struct eeprom_info eeprom_info;
	struct board_configs board_configs;
	struct pcie_usb_configs pcie_usb_configs;
	struct rfic_configs rfic_configs;
	struct ethernet_configs ethernet_configs;
	struct misc_configs misc_configs;
	struct jesd_configs jesd_configs;
} __packed; /*struct eeprom_data */

#endif /* _EEPROM_DATA_H_*/

