
/* SPDX-License-Identifier: GPL-2.0+
 *
 * Copyright (c) 2020 EdgeQ
 */

#ifndef _JESDINIT_H
#define _JESDINIT_H

#define FW_SIZE 0x4000
#define FW_START 0xC000

#define JESD_LINK3_CR_PARA_OFFSET	0x3C450000
#define JESD_LINK3_CR_PARA_LSB		0x3CB602C0
#define JESD_LINK4_CR_PARA_OFFSET	0x3C460000
#define JESD_LINK4_CR_PARA_LSB		0x3C5202C0

#define RF_CARD_METANOIA	0
#define RF_CARD_ADI		1
#define RF_CARD_TYPE_MASK	0x1
#define RF_JESDINIT_BYP_MASK	0x2

#define JESD_LINK_SPEED_8G	0x0
#define JESD_LINK_SPEED_16G	0x2

#define JESD_LINK_3		0x3
#define JESD_LINK_4		0x4
#define JESD_LINK_34		0x34

/* IOSS top registers */
#define JESD_IOSS_TOP_BASE		0x3CB00000
#define JESD_IOSS_TOP_CFG_6		(JESD_IOSS_TOP_BASE + 0x40)
#define JESD_IOSS_TOP_CFG_7		(JESD_IOSS_TOP_BASE + 0x48)
#define JESD_IOSS_TOP_CFG_9		(JESD_IOSS_TOP_BASE + 0x58)
#define JESD_IOSS_TOP_CFG_12		(JESD_IOSS_TOP_BASE + 0x70)
#define JESD_IOSS_TOP_MISC_12		(JESD_IOSS_TOP_BASE + 0x74)
#define JESD_IOSS_TOP_CFG_13		(JESD_IOSS_TOP_BASE + 0x78)
#define JESD_IOSS_TOP_MISC_13		(JESD_IOSS_TOP_BASE + 0x7C)
#define JESD_IOSS_TOP_CFG_16		(JESD_IOSS_TOP_BASE + 0x90)
#define JESD_IOSS_TOP_MISC_16		(JESD_IOSS_TOP_BASE + 0x94)

/* CCIX bring up registers */
#define JESD_CCIX_BRINGUP_BASE		0x3CB40000
#define JESD_CCIX_BRINGUP_CFG_18	(JESD_CCIX_BRINGUP_BASE + 0xB0)
#define JESD_LINK3_IO_CTRL_CFG_31	(JESD_LINK3_IO_CTRL_BASE + 0x118)

/* SERDES Control registers */
#define JESD_LINK3_SERDES_CTRL_BASE	0x3CB60000
#define JESD_LINK3_SERDES_CTRL_CFG_85	(JESD_LINK3_SERDES_CTRL_BASE + 0x2C0)

#define JESD_LINK4_SERDES_CTRL_BASE	0x3C520000
#define JESD_LINK4_SERDES_CTRL_CFG_85	(JESD_LINK4_SERDES_CTRL_BASE + 0x2C0)

/* JESD TX registers */
#define JESD_TX_BASE			0x3CBC0000
#define JESD_TX_CFG_0			(JESD_TX_BASE + 0x20)
#define JESD_TX_SERDES_LANE_MUX_CFG	(JESD_TX_BASE + 0xF0)
#define JESD_TX_SERDES_MISC_0		(JESD_TX_BASE + 0xF4)
#define JESD_TX_CLK_CHAR_DIV_RATIO	(JESD_TX_BASE + 0x108)
#define JESD_TX_SERDES_CLK_SRC_SELECT	(JESD_TX_BASE + 0x110)

/* JESD RX registers */
#define JESD_RX_BASE			0x3CBE0000
#define JESD_RX_CFG_0			(JESD_RX_BASE + 0x20)
#define JESD_RX_SERDES_LANE_MUX_CFG	(JESD_RX_BASE + 0xE8)
#define JESD_RX_MISC_0			(JESD_RX_BASE + 0xEC)

/* I/O Control registers */
#define JESD_LINK3_IO_CTRL_BASE		0x3C4A0000
#define JESD_LINK3_IO_CTRL_CFG_16	(JESD_LINK3_IO_CTRL_BASE + 0xA0)
#define JESD_LINK3_IO_CTRL_MISC_16	(JESD_LINK3_IO_CTRL_BASE + 0xA4)
#define JESD_LINK3_IO_CTRL_CFG_17	(JESD_LINK3_IO_CTRL_BASE + 0xA8)
#define JESD_LINK3_IO_CTRL_CFG_21	(JESD_LINK3_IO_CTRL_BASE + 0xC8)
#define JESD_LINK3_IO_CTRL_MISC_21	(JESD_LINK3_IO_CTRL_BASE + 0xCC)
#define JESD_LINK3_IO_CTRL_CFG_22	(JESD_LINK3_IO_CTRL_BASE + 0xD0)
#define JESD_LINK3_IO_CTRL_CFG_26	(JESD_LINK3_IO_CTRL_BASE + 0xF0)
#define JESD_LINK3_IO_CTRL_MISC_26	(JESD_LINK3_IO_CTRL_BASE + 0xF4)
#define JESD_LINK3_IO_CTRL_CFG_27	(JESD_LINK3_IO_CTRL_BASE + 0xF8)
#define JESD_LINK3_IO_CTRL_CFG_31	(JESD_LINK3_IO_CTRL_BASE + 0x118)
#define JESD_LINK3_IO_CTRL_MISC_31	(JESD_LINK3_IO_CTRL_BASE + 0x11C)
#define JESD_LINK3_IO_CTRL_CFG_32	(JESD_LINK3_IO_CTRL_BASE + 0x120)
#define JESD_LINK3_IO_CTRL_CFG_33	(JESD_LINK3_IO_CTRL_BASE + 0x128)
#define JESD_LINK3_IO_CTRL_CFG_36	(JESD_LINK3_IO_CTRL_BASE + 0x140)
#define JESD_LINK3_IO_CTRL_MISC_36	(JESD_LINK3_IO_CTRL_BASE + 0x144)
#define JESD_LINK3_IO_CTRL_CFG_37	(JESD_LINK3_IO_CTRL_BASE + 0x148)
#define JESD_LINK3_IO_CTRL_CFG_40	(JESD_LINK3_IO_CTRL_BASE + 0x160)
#define JESD_LINK3_IO_CTRL_MISC_40	(JESD_LINK3_IO_CTRL_BASE + 0x164)
#define JESD_LINK3_IO_CTRL_CFG_41	(JESD_LINK3_IO_CTRL_BASE + 0x168)
#define JESD_LINK3_IO_CTRL_CFG_44	(JESD_LINK3_IO_CTRL_BASE + 0x180)
#define JESD_LINK3_IO_CTRL_MISC_44	(JESD_LINK3_IO_CTRL_BASE + 0x184)
#define JESD_LINK3_IO_CTRL_CFG_45	(JESD_LINK3_IO_CTRL_BASE + 0x188)
#define JESD_LINK3_IO_CTRL_CFG_48	(JESD_LINK3_IO_CTRL_BASE + 0x1A0)
#define JESD_LINK3_IO_CTRL_MISC_48	(JESD_LINK3_IO_CTRL_BASE + 0x1A4)
#define JESD_LINK3_IO_CTRL_CFG_50	(JESD_LINK3_IO_CTRL_BASE + 0x1B0)

#define JESD_LINK4_IO_CTRL_BASE		0x3C480000
#define JESD_LINK4_IO_CTRL_CFG_16	(JESD_LINK4_IO_CTRL_BASE + 0xA0)
#define JESD_LINK4_IO_CTRL_MISC_16	(JESD_LINK4_IO_CTRL_BASE + 0xA4)
#define JESD_LINK4_IO_CTRL_CFG_17	(JESD_LINK4_IO_CTRL_BASE + 0xA8)
#define JESD_LINK4_IO_CTRL_CFG_21	(JESD_LINK4_IO_CTRL_BASE + 0xC8)
#define JESD_LINK4_IO_CTRL_MISC_21	(JESD_LINK4_IO_CTRL_BASE + 0xCC)
#define JESD_LINK4_IO_CTRL_CFG_22	(JESD_LINK4_IO_CTRL_BASE + 0xD0)
#define JESD_LINK4_IO_CTRL_CFG_26	(JESD_LINK4_IO_CTRL_BASE + 0xF0)
#define JESD_LINK4_IO_CTRL_MISC_26	(JESD_LINK4_IO_CTRL_BASE + 0xF4)
#define JESD_LINK4_IO_CTRL_CFG_27	(JESD_LINK4_IO_CTRL_BASE + 0xF8)
#define JESD_LINK4_IO_CTRL_CFG_31	(JESD_LINK4_IO_CTRL_BASE + 0x118)
#define JESD_LINK4_IO_CTRL_MISC_31	(JESD_LINK4_IO_CTRL_BASE + 0x11C)
#define JESD_LINK4_IO_CTRL_CFG_32	(JESD_LINK4_IO_CTRL_BASE + 0x120)
#define JESD_LINK4_IO_CTRL_CFG_33	(JESD_LINK4_IO_CTRL_BASE + 0x128)
#define JESD_LINK4_IO_CTRL_CFG_36	(JESD_LINK4_IO_CTRL_BASE + 0x140)
#define JESD_LINK4_IO_CTRL_MISC_36	(JESD_LINK4_IO_CTRL_BASE + 0x144)
#define JESD_LINK4_IO_CTRL_CFG_37	(JESD_LINK4_IO_CTRL_BASE + 0x148)
#define JESD_LINK4_IO_CTRL_CFG_40	(JESD_LINK4_IO_CTRL_BASE + 0x160)
#define JESD_LINK4_IO_CTRL_MISC_40	(JESD_LINK4_IO_CTRL_BASE + 0x164)
#define JESD_LINK4_IO_CTRL_CFG_41	(JESD_LINK4_IO_CTRL_BASE + 0x168)
#define JESD_LINK4_IO_CTRL_CFG_44	(JESD_LINK4_IO_CTRL_BASE + 0x180)
#define JESD_LINK4_IO_CTRL_MISC_44	(JESD_LINK4_IO_CTRL_BASE + 0x184)
#define JESD_LINK4_IO_CTRL_CFG_45	(JESD_LINK4_IO_CTRL_BASE + 0x188)
#define JESD_LINK4_IO_CTRL_CFG_48	(JESD_LINK4_IO_CTRL_BASE + 0x1A0)
#define JESD_LINK4_IO_CTRL_MISC_48	(JESD_LINK4_IO_CTRL_BASE + 0x1A4)
#define JESD_LINK4_IO_CTRL_CFG_50	(JESD_LINK4_IO_CTRL_BASE + 0x1B0)

struct rfic_info {
	u8 rf1_card_type;
	u8 rf2_card_type;
	u16 link3_lane_select;
	u16 link4_lane_select;
	u8 link3_lane_polarity;
	u8 link4_lane_polarity;
	u8 link_speed;
} __packed;

extern uint32_t top_fw[];
extern uint32_t bot_fw[];
extern struct rfic_info rf_info;

void jesd_phy_pwrup(void);
void cpu_rmw_w(u32 addr, u32 mask, u32 wdata);
void cpu_wr_w(u32 addr, u32 wdata);
u32 cpu_rd_w(u32 addr);

#endif
